### ISSUE TITLE
Online demo down

### ISSUE THREAD

**Issue by LaurensRietveld** [angelozerr/CodeMirror-XQuery#14]
The online demo seems to be down:
http://codemirror-java.opensagres.eu.cloudbees.net/xquery.html

**Comment by angelozerr** [comment]
Yes I know, Cloudbees doesn't provide today teh capability to deploy webapp -(

**Comment by angelozerr** [comment]
Please try now http://demo-angelozerr.rhcloud.com/CodeMirror-Java/xquery.html

**Comment by LaurensRietveld** [comment]
it works, thanks!
